import React from 'react';
import Markdown from 'react-markdown';

const CreationItem: React.FC<{ item: any }> = ({ item }) => {
    const [expanded, setExpanded] = React.useState(false);

    return (
        <div onClick={()=>setExpanded(!expanded)} className='p-4 max-w-5xl text-sm bg-white border border-gray-200 rounded-lg cursor-pointer'>
            <div className='flex justify-between items-center gap-4'>
                 <div>
                    <h2 className='font-semibold'>{item.prompt}</h2>
                    <p className='text-gray-500 font-semibold'>{item.type}-{new Date(item.created_at).toLocaleDateString()}</p>
                 </div>
                 <button className='text-blue-800 border border-blue-800 bg-blue-100 pl-2 pr-2 p-1 rounded-2xl'>{item.type}</button>
            </div>
            {
                expanded && (
                    <div>
                        {item.type === 'image'?(
                            <div>
                                <img src={item.content} alt='image' className='mt-3 w-full max-w-md'/>
                            </div>
                        ):(
                            <div className='mt-3 h-full overflow-y-scroll text-sm text-slate-800'>
                               <div>
                                {/* //markdown is used to remove unnecessary *#@ and all such things from the content generated by model to be displayed */}
                                <Markdown>
                                    {item.content}
                                </Markdown>
                                   
                               </div>
                               </div>
                        )}
                        </div>
                )
            }
            
        </div>
    )
}

export default CreationItem;